consul:
  build: consul/
  hostname: consul
  ports:
    - "53:53/udp"
    - "8500:8500"
  command: agent -server -bootstrap-expect 1 -config-dir /consul/conf.d -advertise 192.168.147.130 -client 0.0.0.0
  volumes:
    - ./consul/assets/conf.d:/consul/conf.d
  environment:
      - "SERVICE_NAME=consul"
      - "SERVICE_TAGS=consul"

registrator:
  image: gliderlabs/registrator:latest
  command: -ip=192.168.147.130 consul://consul:8500
  links:
    - consul:consul
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro


nginxgen:
  build: nginxgen/
  hostname: nginxgen
  ports:
    - "80:80"
  links:
    - consul:consul
  environment:
    - "CONSUL=consul:8500"
    - "SERVICE_NAME=nginxgen"
    - "SERVICE_TAGS=nginx"

vault:
  build: vault/
  hostname: vault
  ports:
    - "8200:8200"
  command: server -config=/vault/conf.d/vault.hcl
  links:
    - consul:consul
  volumes:
    - ./vault/assets/conf.d:/vault/conf.d
  environment:
    - "SERVICE_NAME=vault"
    - "SERVICE_TAGS=vault"
    - "VAULT_ADDR=http://0.0.0.0:8200"
